# Generated by Django 4.0.1 on 2022-01-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=255)),
                ('Password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=255)),
                ('Serial', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Date', models.DateField()),
                ('Area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.areas')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.states')),
                ('Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.types')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.users')),
            ],
        ),
    ]
