# Generated by Django 4.0.1 on 2022-01-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
